baseURL: https://centurio.net
disablePathToLower: true
languageCode: en-us
title: Centurios Blog
theme: "stack"
enableGitInfo: true

frontmatter:
  lastmod: ['lastmod', ':git', 'date', 'publishDate']

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 1

  disablePathToLower: false
permalinks:
  post: "/:year/:month/:day/:title/"

params:
  rssFullContent: true
  article:
    toc: true
    readingTime: true
  comments:
    enabled: false
  sidebar:
    subtitle: Macs, Linux, IoT and Photography
    avatar:
      enabled: true
      local: true
      src: img/avatar.png
  widgets:
    enabled:
      - search
      - categories
      - archives
      - tag-cloud
    archives:
      limit: 5
    tagCloud:
      limit: 10
    categoriesCloud:
      limit: 20

menu:
    main:
        - identifier: github
          name: GitHub
          url: 'https://github.com/rudelm/'
          params:
            icon: github
            newTab: true
        
        - identifier: mastodon
          name: Mastodon
          url: 'https://infosec.exchange/@rudelm'
          params:
            icon: mastodon
            rel: me
            newTab: true

        - identifier: twitter
          name: Twitter
          url: 'https://twitter.com/rudelm'
          params:
            icon: twitter
            newTab: true