baseURL: https://centurio.net
languageCode: en-us
title: Centurios Blog
theme: "stack"
enableGitInfo: true
# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

frontmatter:
  lastmod: ['lastmod', ':git', 'date', 'publishDate']

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 1

  disablePathToLower: false
permalinks:
  post: "/:year/:month/:day/:title/"

privacy:
  youtube:
    privacyEnhanced: true

params:
  rssFullContent: true
  article:
    toc: true
    readingTime: true
  comments:
    enabled: false
  sidebar:
    subtitle: Macs, Linux, IoT and Photography
    avatar:
      enabled: true
      local: true
      src: img/avatar.png
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
            limit: 5
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

menu:
  social:
    - identifier: github
      name: GitHub
      url: 'https://github.com/rudelm/'
      params:
        icon: github
        newTab: true
    
    - identifier: mastodon
      name: Mastodon
      url: 'https://infosec.exchange/@rudelm'
      params:
        icon: mastodon
        newTab: true
